
class AgentID:

    MAIN = "MAIN"
    MAIN_ACTION_HANDLER = "MAIN_ACTION_HANDLER"
    OUTPUT_HANDLER = "OUTPUT_HANDLER"
    HISTORY_MANAGER = "HISTORY_MANAGER"
    USER_INTENT_ROUTER = "USER_INTENT_ROUTER"
    PLANNER = "PLANNER"

    LLM_TASK_INITIALIZER = "LLM_TASK_INITIALIZER"
    INPUT_DATA_EDITOR = "INPUT_DATA_EDITOR"
    TASK_GOAL_EDITOR = "TASK_GOAL_EDITOR"
    TASK_DETAILED_INSTRUCTIONS_EDITOR = "TASK_DETAILED_INSTRUCTIONS_EDITOR"
    TASK_GLOBAL_GUIDELINES_EDITOR = "TASK_GLOBAL_GUIDELINES_EDITOR"
    TASK_AUTHOR_NOTES_EDITOR = "TASK_AUTHOR_NOTES_EDITOR"
    INPUT_SCHEMA_EDITOR = "INPUT_SCHEMA_EDITOR"
    OUTPUT_SCHEMA_EDITOR = "OUTPUT_SCHEMA_EDITOR"
    user = "user"
    
