
class AgentID:

    MAIN = "MAIN"
    MAIN_ACTION_HANDLER = "MAIN_ACTION_HANDLER"
    OUTPUT_HANDLER = "OUTPUT_HANDLER"
    HISTORY_MANAGER = "HISTORY_MANAGER"
    USER_INTENT_ROUTER = "USER_INTENT_ROUTER"
    LLM_TASK_INITIALIZER = "LLM_TASK_INITIALIZER"
    user = "user"
    
